# Generated by Django 3.1.7 on 2021-03-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(blank=True, max_length=250)),
                ('Last_Name', models.CharField(blank=True, max_length=250)),
                ('Company', models.CharField(blank=True, max_length=250)),
                ('Website', models.CharField(blank=True, max_length=250)),
                ('Title', models.CharField(blank=True, max_length=250)),
                ('Email', models.CharField(blank=True, max_length=250)),
                ('Email_Confidence', models.CharField(blank=True, max_length=250)),
                ('Address', models.CharField(blank=True, max_length=250)),
                ('Primary_Department', models.CharField(blank=True, max_length=250)),
                ('Secondary_Department', models.CharField(blank=True, max_length=250)),
                ('Level', models.CharField(blank=True, max_length=250)),
                ('Street', models.CharField(blank=True, max_length=250)),
                ('City', models.CharField(blank=True, max_length=250)),
                ('State', models.CharField(blank=True, max_length=250)),
                ('Zip', models.CharField(blank=True, max_length=250)),
                ('Country', models.CharField(blank=True, max_length=250)),
                ('LinkedIn', models.CharField(blank=True, max_length=250)),
                ('Twitter', models.CharField(blank=True, max_length=250)),
                ('Facebook', models.CharField(blank=True, max_length=250)),
                ('Industry', models.CharField(blank=True, max_length=250)),
                ('Company_Headcount', models.CharField(blank=True, max_length=250)),
                ('Company_Revenue', models.CharField(blank=True, max_length=250)),
                ('Direct_Dial', models.CharField(blank=True, max_length=250)),
                ('Mobile_Number', models.CharField(blank=True, max_length=250)),
                ('Company_Number', models.CharField(blank=True, max_length=250)),
                ('Other_Number', models.CharField(blank=True, max_length=250)),
                ('Email_Encrypt', models.CharField(blank=True, max_length=250)),
                ('Mobile_Number_Encrypt', models.CharField(blank=True, max_length=250)),
            ],
        ),
    ]
